### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mmazzarolo** [derektu/react-native-android-btserial#1]
Hello there,
first of all thank you for this awesome module.

In the next months my company ([mostaza](https://github.com/themostaza)) will probably work on btserial communications on react-native (for both iOS and Android), so I'd like to ask you if you are aiming at maintaining this module or if it's just a little side project...  

I'm still new to the bluetooth serial communication stuff and our project will start the next month but if you need any help in the future don't hesitate to contact us 👍

**Comment by derektu** [comment]
This is side project for me right now, don't know how much time i can spend on it. Currently i am using this module to control bluetooth on arduino, and have not tried other setup yet. But I do plan to add device discovery features, and also support iOS.
